config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from mailing.views import base_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('accounts/', include([
        path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login')])),
    path('', base_view, name='main'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import include, path

from mailing.apps import MailingConfig
from mailing.views import (MailingAttemptListView, MailingCreateView, MailingDeleteView, MailingDetailView,
                           MailingListView, MailingUpdateView, MessageCreateView, MessageDeleteView, MessageDetailView,
                           MessageListView, MessageUpdateView, RecipientCreateView, RecipientDeleteView,
                           RecipientDetailView, RecipientListView, RecipientUpdateView, complete_mailing_view,
                           main_page, send_mailing_view, start_mailing_view)

app_name = MailingConfig.name

urlpatterns = [
    path('', main_page, name='main'),
    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/new/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/edit/', MessageUpdateView.as_view(), name='message_edit'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    path('recipient/', RecipientListView.as_view(), name='recipient_list'),
    path('recipient/<int:pk>/', RecipientDetailView.as_view(), name='recipient_detail'),
    path('recipient/new/', RecipientCreateView.as_view(), name='recipient_create'),
    path('recipient/<int:pk>/edit/', RecipientUpdateView.as_view(), name='recipient_edit'),
    path('recipient/<int:pk>/delete/', RecipientDeleteView.as_view(), name='recipient_delete'),
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/new/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/edit/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailing/<int:mailing_id>/start/', start_mailing_view, name='start_mailing'),
    path('mailing/<int:mailing_id>/complete/', complete_mailing_view, name='complete_mailing'),
    path('mailing/<int:mailing_id>/send/', send_mailing_view, name='send_mailing'),
    path('attempts/', MailingAttemptListView.as_view(), name='mailing_attempt_list'),
    path('users/<int:user_id>/toggle/', include('users.urls')),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (RegisterView, edit_profile, email_verification, toggle_user_status, user_list,
                         view_own_profile, view_profile)

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', LogoutView.as_view(next_page='main'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('profile/edit/', edit_profile, name='edit_profile'),
    path('profile/<int:pk>/', view_profile, name='profile'),
    path('profile/', view_own_profile, name='profile_own'),
    path('', user_list, name='user_list'),
    path('<int:user_id>/toggle/', toggle_user_status, name='toggle_user_status'),
]

mailing/models.py
from django.conf import settings
from django.db import models


class Recipient(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='recipients', default=1)
    email = models.EmailField(
        max_length=254,
        unique=True,
        verbose_name="Email",
        help_text="Введите email",
    )
    name = models.CharField(
        max_length=250,
        verbose_name="Ф.И.О",
        help_text="Укажите фамилию, имя, отчество",
    )
    comment = models.TextField(
        verbose_name="Комментарий",
        help_text="Напишите комментарий",
    )

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'получатель'
        verbose_name_plural = 'получатели'
        ordering = ['email', 'name']
        permissions = [
            ("can_view_recipient", "Может просматривать получателя"),
        ]


class Message(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='messages', default=1)
    subject_letter = models.CharField(
        max_length=200, verbose_name='Тема письма', help_text='Укажите тему письма',
    )
    body_letter = models.TextField(
        verbose_name="Тело письма",
        help_text="Укажите текст письма",
    )

    def __str__(self):
        return self.subject_letter

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'
        ordering = ['subject_letter']
        permissions = [
            ("can_view_message", "Можно просмотреть сообщение"),
        ]


class Mailing(models.Model):
    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('running', 'Запущена'),
        ('completed', 'Завершена'),
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='mailings', default=1)
    first_send_datetime = models.DateTimeField(
        verbose_name="Дата и время первой отправки",
        blank=True,
        null=True,
        help_text="Дата и время первой отправки (может быть пустым, если рассылка еще не запущена)",
    )

    end_send_datetime = models.DateTimeField(
        verbose_name="Дата и время окончания отправки",
        blank=True,
        null=True,
        help_text="Дата и время окончания отправки (может быть пустым, если рассылка еще не завершена)",
    )

    status = models.CharField(
        verbose_name="Статус",
        max_length=20,
        choices=STATUS_CHOICES,
        default='Создана',
    )
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    recipient = models.ManyToManyField(Recipient)

    def update_status(self):
        """Обновляет статус рассылки на основе дат отправки."""
        if self.end_send_datetime:
            self.status = 'completed'
        elif self.first_send_datetime:
            self.status = 'running'
        else:
            self.status = 'created'

    def save(self, *args, **kwargs):
        """Переопределяем метод save для автоматического обновления статуса."""
        self.update_status()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Рассылка {self.pk} - {self.status}"

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ['status']
        permissions = [
            ("can_set_mailing_status", "Можно установить статус рассылки"),
            ("can_disable_mailing", "Может отключать рассылку"),
            ("can_complete_mailing", "Может завершать рассылку"),
            ("can_view_all_mailings", "Может просмотреть все рассылки"),
        ]


class MailingAttempt(models.Model):
    STATUS_CHOICES = [
        ('successfully', 'Успешно'),
        ('not successfully', 'Не успешно'),
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    attempt_datetime = models.DateTimeField(
        verbose_name="Дата и время попытки",
        auto_now_add=True,
        help_text="Дата и время попытки",
    )

    status = models.CharField(
        verbose_name="Статус",
        max_length=20,
        choices=STATUS_CHOICES,
    )

    mail_server_response = models.TextField(
        verbose_name="Ответ почтового сервера",
    )

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)

    def __str__(self):
        return f"Попытка рассылки {self.mailing} - {self.attempt_datetime}"

    class Meta:
        verbose_name = "Попытка"
        verbose_name_plural = "Попытки"

mailing/forms.py
from django.forms import BooleanField, ModelForm

from mailing.models import Mailing, Message, Recipient


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = 'form-check-input'
            else:
                fild.widget.attrs['class'] = 'form-control'


class MailingForm(ModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['recipient'].queryset = Recipient.objects.filter(user=user)
        self.fields['message'].queryset = Message.objects.filter(user=user)

    class Meta:
        model = Mailing
        fields = ['message', 'recipient', 'status']

mailing/templates/base.html
<!doctype html>
{% load user_filters %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block name %}WBRus{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="bg-body-tertiary">
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">WBRus</a>
    <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'mailing:main' %}">Главная</a>
        </li>
        {% if user|in_group:"Модераторы" %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:user_list' %}">Список пользователей</a>
            </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:profile_own' %}">Профиль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mailing:message_list' %}">Сообщения</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mailing:recipient_list' %}">Получатели</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mailing:mailing_list' %}">Рассылки</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mailing:mailing_attempt_list' %}">Попытки</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <form method='post' action="{% url 'users:logout' %}">
            {% csrf_token %}
            <button class="nav-link">Выход</button>
          </form>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Вход</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="Поиск" placeholder="Поиск" aria-label="Поиск">
        <button class="btn btn-outline-success" type="submit">Поиск</button>
      </form>
    </div>
  </div>
</nav>
<main class="container">
  <div class="d-flex align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
  </div>
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    {% block content %}
    {% endblock %}
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

mailing/templates/mailing_attempt_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
  <h1 class="mb-4">История попыток отправки</h1>
  <ul>
    {% for attempt in attempts %}
       <li class="list-group-item">
        <strong>Дата:</strong> {{ attempt.attempt_datetime }}<br>
        <strong>Статус:</strong> {{ attempt.get_status_display }}<br>
        <strong>Ответ сервера:</strong> {{ attempt.mail_server_response }}<br>
        <strong>Рассылка:</strong> <a href="{% url 'mailing:mailing_detail' attempt.mailing.pk %}">{{ attempt.mailing.message.subject_letter }}</a>
      </li>
    {% empty %}
      <li>Нет попыток отправки.</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

mailing/templates/mailing_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Удалить рассылку</h1>
    <p>Вы уверены, что хотите удалить "{{ mailing.message }}"?</p>
    {% if mailing.user == user or perms.user.mailing_delete %}
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-dark rounded-pill px-3">Удалить</button>
            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-dark rounded-pill px-3">Отмена</a>
        </form>
    {% else %}
        <p>У вас нет прав на удаление этой рассылки.</p>
        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-dark rounded-pill px-3">Вернуться к списку</a>
    {% endif %}
</div>
{% endblock %}

mailing/templates/mailing_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h1>Рассылка: {{ mailing.message }}</h1>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li
        {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% if mailing.user == user or perms.mailing.can_set_mailing_status %}
    <a href="{% url 'mailing:mailing_edit' mailing.pk %}" class="btn btn-dark rounded-pill px-3">Редактировать</a>
    <a href="{% url 'mailing:mailing_delete' mailing.pk %}" class="btn btn-dark rounded-pill px-3">Удалить</a>
    {% endif %}

    <a href="{% url 'mailing:mailing_list' %}" class="btn btn-dark rounded-pill px-3">Вернуться к списку</a>
</div>
{% endblock %}

mailing/templates/mailing_form.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Создать рассылку</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark rounded-pill px-3">Сохранить</button>
        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-dark rounded-pill px-3">Отмена</a>
    </form>
</div>
{% endblock %}

mailing/templates/main.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h2 class="border-bottom pb-2 mb-0">Добро пожаловать</h2>
    <div class="d-flex text-body-secondary pt-3">
        <div class="pb-4 mb-0 small lh-sm border-bottom w-100">
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Всего рассылок:</strong>
                <span>{{ total_mailings }}</span>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Активных рассылок:</strong>
                <span>{{ active_mailings }}</span>
            </div>
            <div class="d-flex justify-content-between">
                <strong class="text-gray-dark">Уникальных получателей:</strong>
                <span>{{ unique_clients }}</span>
            </div>
            <div class="d-flex justify-content-between align-items-center">
                <strong class="text-gray-dark">Всего попыток рассылок:</strong>
                <span>{{ total_attempts }}</span>
            </div>
            <div class="d-flex justify-content-between align-items-center">
                <strong class="text-gray-dark">Успешных попыток рассылок:</strong>
                <span>{{ successful_attempts }}</span>
            </div>
            <div class="d-flex justify-content-between align-items-center">
                <strong class="text-gray-dark">Неуспешных попыток рассылок:</strong>
                <span>{{ failed_attempts }}</span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/message_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Удалить сообщение</h1>
    <p>Вы уверены, что хотите удалить "{{ message.subject_letter }}"?</p>
    {% if perms.user.message_delete or message.user == user %}
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-dark rounded-pill px-3">Удалить</button>
            <a href="{% url 'mailing:message_list' %}" class="btn btn-dark rounded-pill px-3">Отмена</a>
        </form>
    {% else %}
        <p>У вас нет прав на удаление этого сообщения.</p>
        <a href="{% url 'mailing:message_list' %}" class="btn btn-dark rounded-pill px-3">Вернуться к списку</a>
    {% endif %}
</div>
{% endblock %}

mailing/templates/message_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">{{ message.subject_letter }}</h1>
    <p>{{ message.body_letter }}</p>

    {% if message.user == user or perms.user.mailing.can_view_message %}
    <a href="{% url 'mailing:message_edit' message.pk %}" class="btn btn-dark rounded-pill px-3">Редактировать</a>
    <a href="{% url 'mailing:message_delete' message.pk %}" class="btn btn-dark rounded-pill px-3">Удалить</a>
    {% endif %}

    <a href="{% url 'mailing:message_list' %}" class="btn btn-dark rounded-pill px-3">Вернуться к списку</a>
</div>
{% endblock %}

mailing/templates/message_form.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Создать сообщение</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark rounded-pill px-3">Сохранить</button>
        <a href="{% url 'mailing:message_list' %}" class="btn btn-dark rounded-pill px-3">Отмена</a>
    </form>
</div>
{% endblock %}

mailing/templates/message_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h6 class="border-bottom pb-2 mb-0">Ваши сообщения</h6>
    <ul class="list-group">
        {% for message in messages %}
        <li class="list-group-item">
            <a href="{% url 'mailing:message_detail' message.pk %}">{{ message.subject_letter }}</a>
            {% if message.can_change %}
                <a href="{% url 'mailing:message_edit' message.pk %}" class="btn btn-dark rounded-pill px-3">Редактировать</a>
                <a href="{% url 'mailing:message_delete' message.pk %}" class="btn btn-dark rounded-pill px-3">Удалить</a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    <div class="d-flex justify-content-end pt-3">
        {% if user.is_authenticated %}
        <a href="{% url 'mailing:message_create' %}" class="btn btn-dark rounded-pill px-3">Создать сообщение</a>
        {% endif %}
    </div>
</div>
{% endblock %}

mailing/templates/recipient_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Удалить получателя</h1>
    <p>Вы уверены, что хотите удалить "{{ recipient.email }}"?</p>
    {% if recipient.user == user or perms.user.recipient_delete %}
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-dark rounded-pill px-3">Удалить</button>
        <a href="{% url 'mailing:recipient_list' %}" class="btn btn-dark rounded-pill px-3">Отмена</a>
    </form>
    {% else %}
    <p>У вас нет прав на удаление этого получателя.</p>
    <a href="{% url 'mailing:recipient_list' %}" class="btn btn-dark rounded-pill px-3">Вернуться к списку</a>
    {% endif %}
</div>
{% endblock %}

mailing/templates/recipient_detail.html
{% extends "base.html" %}

{% block content %}
{% load cache %}

{% cache 60 * 5 template_fragment_name some_variable %}
<div class="container mt-5">
    <h1 class="mb-4">{{ recipient.email }}</h1>
    <p> Email: {{ recipient.email }}</p>
    <p> ФИО: {{ recipient.name }}</p>
    <p> Комментарий: {{ recipient.comment }}</p>
    {% endcache %}

    {% if recipient.user == user or perms.user.mailing.can_view_recipient %}
    <a href="{% url 'mailing:recipient_edit' recipient.pk %}" class="btn btn-dark rounded-pill px-3">Редактировать</a>
    <a href="{% url 'mailing:recipient_delete' recipient.pk %}" class="btn btn-dark rounded-pill px-3">Удалить</a>
    {% endif %}

    <a href="{% url 'mailing:recipient_list' %}" class="btn btn-dark rounded-pill px-3">Вернуться к списку</a>
</div>
{% endblock %}

mailing/templates/recipient_form.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Создать получателя</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark rounded-pill px-3">Сохранить</button>
        <a href="{% url 'mailing:recipient_list' %}" class="btn btn-dark rounded-pill px-3">Отмена</a>
    </form>
</div>
{% endblock %}

mailing/templates/recipient_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h6 class="border-bottom pb-2 mb-0">Ваши получатели</h6>
    <ul class="list-group">
        {% for recipient in recipients %}
        <li class="list-group-item">
            <a href="{% url 'mailing:recipient_detail' recipient.pk %}">{{ recipient.email }}</a>
            {% if recipient.can_change %}
                <a href="{% url 'mailing:recipient_edit' recipient.pk %}" class="btn btn-dark rounded-pill px-3">Редактировать</a>
                <a href="{% url 'mailing:recipient_delete' recipient.pk %}" class="btn btn-dark rounded-pill px-3">Удалить</a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    <div class="d-flex justify-content-end pt-3">
            {% if user.is_authenticated %}
            <a href="{% url 'mailing:recipient_create' %}" class="btn btn-dark rounded-pill px-3">Создать получателя</a>
            {% endif %}
        </div>
    </div>
{% endblock %}